tempest.api.compute.admin.test_aggregates.AggregatesAdminTestJSON.test_aggregate_add_host_create_server_with_az.*: "No valid host was found. There are not enough hosts available."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_duplicate.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_invalid_from_port.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_invalid_id.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_invalid_ip_protocol.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_invalid_port_range.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_invalid_to_port.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_create_security_group_rule_with_non_existent_id.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.security_groups.test_security_group_rules_negative.SecurityGroupRulesNegativeTestJSON.test_delete_security_group_rule_with_non_existent_id.*: "Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_device_tagging.TaggedAttachmentsTest.test_tagged_attachment.*: "Command: 'set -eu -o pipefail; PATH=$PATH:/sbin:/usr/sbin; curl http://169.254.169.254/openstack/latest/meta_data.json' executed on host '195.169.22.157'."
tempest.api.compute.servers.test_device_tagging.TaggedBootDevicesTest_v242.test_tagged_boot_devices.*: "Command: 'set -eu -o pipefail; PATH=$PATH:/sbin:/usr/sbin; curl http://169.254.169.254/openstack/latest/meta_data.json' executed on host '195.169.22.63'."
tempest.api.compute.servers.test_device_tagging.TaggedBootDevicesTest.test_tagged_boot_devices.*: "curl: (56) Recv failure: Connection reset by peer"
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_changes_since_future_date.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_changes_since_invalid_date.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_limits_greater_than_actual_count.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_limits_pass_negative_value.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_limits_pass_string.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_non_existing_flavor.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_non_existing_image.*:"Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_by_non_existing_server_name.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_detail_server_is_deleted.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_status_non_existing.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_list_servers_negative.ListServersNegativeTestJSON.test_list_servers_with_a_deleted_server.*: "Unexpected response code received Details: 502."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_create_server_metadata_blank_key.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_delete_metadata_non_existent_server.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_list_server_metadata_non_existent_server.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_metadata_items_limit.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_server_create_metadata_key_too_long.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_server_metadata_non_existent_server.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_set_metadata_invalid_key.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_set_metadata_non_existent_server.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_set_server_metadata_blank_key.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_set_server_metadata_missing_metadata.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_update_metadata_non_existent_server.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_metadata_negative.ServerMetadataNegativeTestJSON.test_update_metadata_with_blank_key.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.test_versions.TestVersions.test_get_version_details.*: "HTTPConnectionPool(host='merlin.hpc.rug.nl', port=8774): Max retries exceeded with url: /v2/ (Caused by ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))."
tempest.api.volume.admin.test_volume_types.VolumeTypesTest.test_volume_crud_with_volume_type_and_extra_specs.*: "volume 95f9fb51-408e-41a3-90fa-81f080638e59 failed to build and is in ERROR status."
tempest.api.volume.admin.test_volumes_backup.VolumesBackupsAdminTest.test_volume_backup_export_import.*: "backup b9d355d9-c343-4013-90af-d1c0bc607c1b failed to build and is in ERROR status."
tempest.api.volume.admin.test_volumes_backup.VolumesBackupsAdminTest.test_volume_backup_reset_status.*: "backup b3819620-39df-4270-b924-43147bec1a88 failed to build and is in ERROR status."
tempest.api.volume.test_volume_delete_cascade.VolumesDeleteCascade.test_volume_from_snapshot_cascade_delete.*: "<map object at 0x7f992d508f40> matches Contains('a0148abd-11c7-4834-a8d3-5f09f8d78a38')."
tempest.api.volume.test_volumes_backup.VolumesBackupsTest.test_backup_create_attached_volume.*: "backup dcd6c3ba-65d4-4304-ba7b-fde5f8b67b9a failed to build and is in ERROR status."
tempest.api.volume.test_volumes_backup.VolumesBackupsTest.test_bootable_volume_backup_and_restore.*: "backup 7163f79d-47bc-4efe-91b1-dd6ccbc0cb31 failed to build and is in ERROR status."
tempest.api.volume.test_volumes_backup.VolumesBackupsTest.test_volume_backup_create_get_detailed_list_restore_delete.*: "backup c9f311f6-ed8b-4496-ab46-348b15d10561 failed to build and is in ERROR status."
tempest.api.volume.test_volumes_backup.VolumesBackupsV39Test.test_update_backup.*: "backup 98adddc4-adc3-426a-ae68-baf69cde3224 failed to build and is in ERROR status."
tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_details_pagination.*: "'https' != 'http': Incorrect link to next page. URLs do not match at scheme: https://merlin.hpc.rug.nl:8776/v3/4fea5eeb038e40feb9fc88d2ed242e5d/volumes/detail?limit=1&marker=cc059045-2b9d-44d9-be50-2c66207422b9 http://merlin.hpc.rug.nl:8776/v3/4fea5eeb038e40feb9fc88d2ed242e5d/volumes/detail?limit=1&marker=cc059045-2b9d-44d9-be50-2c66207422b9."
tempest.api.volume.test_volumes_list.VolumesListTestJSON.test_volume_list_pagination.*: "'https' != 'http': Incorrect link to next page. URLs do not match at scheme: https://merlin.hpc.rug.nl:8776/v3/4fea5eeb038e40feb9fc88d2ed242e5d/volumes?limit=1&marker=cc059045-2b9d-44d9-be50-2c66207422b9 http://merlin.hpc.rug.nl:8776/v3/4fea5eeb038e40feb9fc88d2ed242e5d/volumes?limit=1&marker=cc059045-2b9d-44d9-be50-2c66207422b9."
tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_backup.*: "backup e0ff298c-ad10-497e-9360-fc0b4240409f failed to build and is in ERROR status."
tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_get_list_update_delete.*: "The server has either erred or is incapable of performing the requested operation."
tempest.api.volume.test_volumes_snapshots.VolumesSnapshotTestJSON.test_snapshot_create_offline_delete_online.*: "The server has either erred or is incapable of performing the requested operation."
tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_mtu_sized_frames.*: "Public network connectivity check failed Timed out waiting for 195.169.22.139 to become reachable."
tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_router_rescheduling.*: "Agent 0d2f07d0-4110-4a2d-90b0-7363c585c8b2 is not a L3 Agent or has been disabled."
tempest.scenario.test_server_basic_ops.TestServerBasicOps.test_server_basic_ops.*: "'set -eu -o pipefail; PATH=$PATH:/sbin:/usr/sbin; curl http://169.254.169.254/latest/meta-data/public-ipv4' executed on host '195.169.22.139'."
tempest.scenario.test_volume_backup_restore.TestVolumeBackupRestore.test_volume_backup_restore.*: "backup 9b9e577f-de10-4015-8de1-14c8bcafb46a failed to build and is in ERROR status."
tempest.scenario.test_volume_boot_pattern.TestVolumeBootPattern.test_image_defined_boot_from_volume.*: "Volume is smaller than the minimum size specified in image metadata. Volume size is 1073741824 bytes, minimum size is 21474836480 bytes."
tempest.api.compute.floating_ips.test_floating_ips_actions.FloatingIPsAssociationTestJSON.test_associate_already_associated_floating_ip.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.floating_ips.test_floating_ips_actions.FloatingIPsAssociationTestJSON.test_associate_disassociate_floating_ip.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')."
tempest.api.compute.servers.test_server_actions.ServerActionsTestJSON.test_get_console_output_server_id_in_shutoff_status.*: "neutronclient.common.exceptions.ServiceUnavailable"
tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_network_basic_ops.*: "Unexpected response code received Details: 502"
tempest.scenario.test_network_basic_ops.TestNetworkBasicOps.test_preserve_preexisting_port.*: "'Connection aborted.', RemoteDisconnected('Remote end closed connection without response')"
